site_name: Мои дела
theme:
  name: readthedocs
nav:
  - Контур: Контур/Контур.md
  - 105 Корус: Корус/Корус.md
  - Exite: Exite/Exite.md
  - arx: arx/arx.md
  - dtv: dtv/dtv.md
  - ehc: ehc/ehc.md
  - ghc: ghc/ghc.md
  - krl: krl/krl.md
  - orl: orl/orl.md
  - srg: srg/srg.md
  - whc: whc/whc.md
  - zrs: zrs/zrs.md
  - sftserv.ru/chronology/DISP/826.htm: index.md
  - Четвёртое ТО: folder/folder.md

# shift alt дублировать строку