site_name: Мои дела
theme:
  name: readthedocs
nav:
  - 192 Контур: Контур/Контур.md
  - 105 Корус: Корус/Корус.md
  - 152 Exite: Exite/Exite.md
  - arx: arx/arx.md
  - dtv: dtv/dtv.md
  - ehc: ehc/ehc.md
  - ghc: ghc/ghc.md
  - ig2: ig2/ig2.md
  - klm: klm/klm.md
  - krl: krl/krl.md
  - orl: orl/orl.md
  - srg: srg/srg.md
  - vor: vor/vor.md
  - whc: whc/whc.md
  - zrs: zrs/zrs.md
  - sftserv.ru/chronology/DISP/826.htm: index.md
  - Информация об организации по GLN: index2.md
  - Четвёртое ТО: folder/folder.md

# shift alt дублировать строку